import{HttpError}from"./errors.js";
const cache=new Map();
function b64(value){const padded=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=");const bytes=Uint8Array.from(atob(padded),c=>c.charCodeAt(0));return bytes}
function decodeJson(value){return JSON.parse(new TextDecoder().decode(b64(value)))}
async function importKey(jwk,alg){if(alg==="RS256")return crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);if(alg==="ES256")return crypto.subtle.importKey("jwk",jwk,{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);throw new HttpError(401,"ACCESS_ALGORITHM_REJECTED","The Cloudflare Access assertion uses an unsupported signing algorithm.")}
async function accessClaims(token,env){const parts=token.split(".");if(parts.length!==3)throw new HttpError(401,"ACCESS_ASSERTION_INVALID","The Cloudflare Access assertion is malformed.");const header=decodeJson(parts[0]),payload=decodeJson(parts[1]);const team=String(env.CF_ACCESS_TEAM_DOMAIN||"").replace(/^https?:\/\//,"").replace(/\/$/,"");if(!team||!env.CF_ACCESS_AUD)throw new HttpError(503,"ACCESS_CONFIGURATION_MISSING","Production studio authorization is not configured.","Set CF_ACCESS_TEAM_DOMAIN and CF_ACCESS_AUD as Worker secrets or variables.");const issuer=`https://${team}`;if(payload.iss!==issuer||payload.aud!==env.CF_ACCESS_AUD&&!(Array.isArray(payload.aud)&&payload.aud.includes(env.CF_ACCESS_AUD)))throw new HttpError(401,"ACCESS_CLAIMS_REJECTED","The Cloudflare Access issuer or audience is not authorized.");const now=Math.floor(Date.now()/1000);if(!payload.exp||payload.exp<now||payload.nbf&&payload.nbf>now+30)throw new HttpError(401,"ACCESS_ASSERTION_EXPIRED","The Cloudflare Access session has expired.");let keys=cache.get(team);if(!keys||keys.expires<Date.now()){const response=await fetch(`${issuer}/cdn-cgi/access/certs`);if(!response.ok)throw new HttpError(503,"ACCESS_KEYS_UNAVAILABLE","Cloudflare Access signing keys could not be loaded.");keys={value:(await response.json()).keys,expires:Date.now()+300000};cache.set(team,keys)}const jwk=keys.value.find(x=>x.kid===header.kid);if(!jwk)throw new HttpError(401,"ACCESS_KEY_UNKNOWN","The Access assertion signing key is unknown.");const key=await importKey(jwk,header.alg);const data=new TextEncoder().encode(`${parts[0]}.${parts[1]}`);let signature=b64(parts[2]);if(header.alg==="ES256")signature=rawEcdsaToDer(signature);const valid=await crypto.subtle.verify(header.alg==="RS256"?{name:"RSASSA-PKCS1-v1_5"}:{name:"ECDSA",hash:"SHA-256"},key,signature,data);if(!valid)throw new HttpError(401,"ACCESS_SIGNATURE_REJECTED","The Cloudflare Access assertion signature is invalid.");return payload}
function rawEcdsaToDer(raw){if(raw.length!==64)return raw;const trim=bytes=>{let i=0;while(i<bytes.length-1&&bytes[i]===0)i++;let value=bytes.slice(i);if(value[0]&0x80){const prefixed=new Uint8Array(value.length+1);prefixed.set(value,1);value=prefixed}return value};const r=trim(raw.slice(0,32)),s=trim(raw.slice(32));const out=new Uint8Array(6+r.length+s.length);out.set([0x30,4+r.length+s.length,0x02,r.length],0);out.set(r,4);out.set([0x02,s.length],4+r.length);out.set(s,6+r.length);return out}
export async function requireOperator(request,env){const workspaceEmail=request.headers.get("oai-authenticated-user-email");if(workspaceEmail)return{id:`workspace:${await hash(workspaceEmail.toLowerCase())}`,displayName:decodeName(request)||workspaceEmail,source:"workspace"};const token=request.headers.get("cf-access-jwt-assertion");if(token){const claims=await accessClaims(token,env);return{id:`access:${claims.sub}`,displayName:claims.name||claims.email||"Cloudflare Access operator",source:"cloudflare-access"}}if(env.ENVIRONMENT!=="production"&&String(env.LOCAL_AUTH_BYPASS)==="true")return{id:"local:operator",displayName:"Local development operator",source:"local-bypass"};throw new HttpError(401,"AUTHENTICATION_REQUIRED","Station Studio authentication is required.","Protect /studio and /api/admin/* with Cloudflare Access, or enable the isolated local bypass outside production.")}
function decodeName(request){const value=request.headers.get("oai-authenticated-user-full-name");if(!value||request.headers.get("oai-authenticated-user-full-name-encoding")!=="percent-encoded-utf-8")return null;try{return decodeURIComponent(value)}catch{return null}}
async function hash(value){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(bytes)].slice(0,12).map(x=>x.toString(16).padStart(2,"0")).join("")}
export function enforceOrigin(request,env){if(["GET","HEAD","OPTIONS"].includes(request.method))return;const origin=request.headers.get("origin"),expected=new URL(request.url).origin,allowed=new Set([expected,...String(env.ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean)]);if(!origin||!allowed.has(origin))throw new HttpError(403,"ORIGIN_REJECTED","This mutation did not come from an authorized station origin.","Use the Studio at the configured station origin.")}
